### ISSUE TITLE
Issue #2(topic creation error)

### ISSUE THREAD

**Issue by ankanbal** [csl-622/user_dynamics#2]
Giving the following errors on running testing.py

Traceback (most recent call last):
  File "testing.py", line 116, in <module>
    nlp = spacy.load('en', disable=['parser', 'ner'])
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by JonStark1** [comment]
Just type, "download en model spacy" on google and you'll find the solution.
